### PR TITLE
Style guide: Update abbreviation rule to note avoidance

### PR DESCRIPTION
**Pull request by mikestreety**

### CODE REVIEW

**Comment by chrisvfritz** [comment]
The rule titles only include the topic, rather than the specific suggestion. 🙂

**Comment by mikestreety** [comment]
Ah ok, thanks @chrisvfritz - I did get a little confused as it says:

> Abbreviations in component names **strongly recommended**

Took me a while to work it out! Is this something I could raise as an issue? Great style guide by the way, massive help!

**Comment by chrisvfritz** [comment]
Ah, I can definitely see how that could be confusing. Thanks for the further explanation! Maybe we should update it to:

> Full-word component names

What do you think?

**Comment by mikestreety** [comment]
Works for me! 👍  updated!

**Comment by chrisvfritz** [comment]
Thanks! 🎉

**Pull request merged**
