### PR TITLE
Updated Vue style guide

### PR DESCRIPTION
**Pull request by dulin666**
I had a small misunderstanding with some lines of code in my team. I think this changes will provide a better approach for development based on Vue style guide.

### CODE REVIEW

**Comment by chrisvfritz** [comment]
We actually don't recommend having `>` on the same line as the last attribute, instead choosing to treat HTML the same way we treat JS. For example, you probably wouldn't write:

``` js
if (
  abc &&
  def ) {
  test
}
```

But rather:

``` js
if (
  abc &&
  def 
) {
  test
}
```

This also makes it easier to rearrange attributes and create cleaner diffs when you add or remove attributes.

**Comment by dulin666** [comment]
Thanks. Sounds good.

**Comment by dulin666** [comment]
I found google HTML / CSS style guide. What do you think about that?
https://google.github.io/styleguide/htmlcssguide.html#HTML_Line-Wrapping

**Comment by chrisvfritz** [comment]
It doesn't change my thoughts, if that's what you're asking. Their more permissive style doesn't offer any advantages I'm aware of.

**Comment by sdras** [comment]
Thanks for the PR! Since we're not going to change this, I'm going to go ahead and close it out. The research here is appreciated, though.

**Pull request closed without merging**
