### PR TITLE
docs(Guide): Update “Essentials” part of Guide

### PR DESCRIPTION
**Pull request by Zearin**
This is a smaller piece of my Pull Request #2491.  It covers just the pages under the “Essentials” section of the Guide.

### CODE REVIEW

**Comment by sdras** [comment]
Thanks for the contribution! Similar in style to other PR we just closed, but also, this PR is very large and difficult to review. 

Some of the changes are things we would welcome, but others are not what we're looking for. I'm sorry, we can't take it in this state, in the future if you communicate what you'd like to change and scope it down a bit, we could do a more thorough review. It's worth mentioning that we're currently revising and migrating content, so this wouldn't be a good time for a major change in terms of timing for the team, either. Once again, thanks for your effort here! It's appreciated.

**Comment by Zearin** [comment]
Look, this Pull Request _IS_ after @phanan reviewed my original Pull Request #2491, and asked me to break it into smaller pieces.  I thought it would be better to make a pull request for each section of the Guide, rather than submitting a separate request for each individual file.

I really wanted to help contribute to the documentation. You’re not making it easy. 

I’ve just wasted an evening on this.  I thought I was using my time to help a project I like, and  following @phanan’s feedback.

My original Pull Request was met with dialogue, feedback, and an invitation to keep trying.  So far, you have closed 2 of my Pull Requests within minutes of their creation—without any dialogue, suggestions for how to get my work merged, or any indication that you want anything except that I give up trying to contribute.

Well, congratulations: you’ve succeeded.

**Comment by sdras** [comment]
I'm sorry to have wasted your time, 21 days ago was before we began the migration, I definitely don't want you to waste work but you stand to waste more effort if we merge in large swaths of content that we are already updating in a different way somewhere else. Please understand that we do value your contribution, however, this PR is _smaller_ than the other one, that doesn't mean it's small enough to break down easily for a reviewer. This is a group project, so we have to work in a way that benefits everyone's time, yours, the teams, and everyone working together.

**Comment by phanan** [comment]
Hey @Zearin, sorry for the trouble. Indeed this is not anyone's fault but my miscommunication 😞. Your work was every bit solid—I've even shared the original PR among the team, which received lots of appreciation. The only problem is we've recently started migrating docs from v2 to v3 with lots of changes to both content and structure. This would, unfortunately, render your changes (and similar PR's to v2 repo), as great as they are, either lost or a pain for v2-v3 synchronization, hence @sdras's decision to skip them for now. 

Don't feel discouraged! While skipped, your work has been both an inspiration and reference for us in the v3 migration, and we're looking forward to your future contributions once v3 comes to public.

**Pull request closed without merging**
