### PR TITLE
Amend doc for new currency argument

### PR DESCRIPTION
**Pull request by phanan**
To follow up with https://github.com/vuejs/vue/pull/2676.

### CODE REVIEW

**Comment by ludo237** [comment]
Is should use the `£` sign to keep it coherent with the previous example

**Comment by phanan** [comment]
Actually the `₫` sign should better demonstrate the purpose of the argument, as VND doesn't have any decimal places.

**Comment by yyx990803** [comment]
I assume most users wouldn't know that symbol stands for VND, and they wouldn't know that VND uses no decimal places, so maybe add a bit of note on that ;)

**Comment by phanan** [comment]
Done.

**Pull request merged**
