### PR TITLE
feat(functional): describe how to pass down attributes

### PR DESCRIPTION
**Pull request by posva**
I see people not knowing this. Latest issue about it https://github.com/vuejs/vue/issues/7554

### CODE REVIEW

**Comment by blake-newman** [comment]
@posva see: https://github.com/vuejs/vue/issues/7557

Relates to this (in particular when not specifying prop definition)

**Comment by chrisvfritz** [comment]
@posva @blake-newman I tweaked the section slightly, noting how this passes event listeners as well and the slight difference from normal components in that case. What do you think?

**Comment by posva** [comment]
Love that last sentence 😆

**Comment by posva** [comment]
LGTM I think the problem specified by Blake is a bit different (it looks like a bug to me)

**Pull request merged**
