### PR TITLE
Change Ctor to Constructor in unit testing portion of guide

### PR DESCRIPTION
**Pull request by p-adams**

### CODE REVIEW

**Comment by chrisvfritz** [comment]
I'm happy to merge this if you revert const back to var (I'm guessing it was included in this PR by mistake). 🙂

**Comment by p-adams** [comment]
const is actually being used here in the docs https://vuejs.org/v2/guide/unit-testing.html

**Comment by chrisvfritz** [comment]
Yes, the `const`s in the unit testing part of the guide were actually good, since unit tests will typically be run in a Node environment. But you've changed `var`s to `const`s in the Essentials of the guide (`src/v2/guide/index.md`) and that's the part I'd like to change back..

**Comment by p-adams** [comment]
Yes, that was a mistake. Thanks for pointing it out!

**Comment by chrisvfritz** [comment]
Looks great! 🙂 🎉

**Pull request merged**
