### PR TITLE
Improvements recipe of Create a CMS-Powered Blog

### PR DESCRIPTION
**Pull request by lex111**

### CODE REVIEW

**Comment by Alex-Sokolov** [comment]
Maybe also change this:
```js
data() {
  return {
    post: {}
  }
},
```

to this:
```js
data() {
  return {
    post: null
  }
},
```

Empty object often not useful in applications & more complicated to track if object is empty

**Comment by lex111** [comment]
@Alex-Sokolov the `v-for` directive requires an array, is not it?

**Comment by Alex-Sokolov** [comment]
@lex111 No, if we change empty object to null, also we need to add v-if for checking, and until post loaded show loading placeholder or smth like that

**Comment by lex111** [comment]
friendly ping @sdras

**Comment by sdras** [comment]
Much better formatting, thank you for this.

**Pull request merged**
