### PR TITLE
Document changes in inject definition for feature vuejs/vue#6097

### PR DESCRIPTION
**Pull request by pdanpdan**
Allow defining optional inject dependency with default values (vuejs/vue#6322, vuejs/vue#6097).

### CODE REVIEW

**Comment by chrisvfritz** [comment]
@pdanpdan I tweaked it slightly to make the options a little easier to read. Otherwise looks good! Let me know when that PR is merged and we'll merge this too. 🙂 👍

**Comment by pdanpdan** [comment]
Sure, thank you.

**Comment by chrisvfritz** [comment]
@pdanpdan I see that the PR is merged now. Are there any changes that need to be made here from  a technical perspective?

**Comment by pdanpdan** [comment]
No. This PR is still valid. I think it would apply from the next release.

**Comment by chrisvfritz** [comment]
Excellent. Then I'll just make a couple small content changes, so that it's ready when we next release comes along.

**Comment by sdras** [comment]
Hey all, this is a pretty old PR now, does anyone know the status of it?

**Pull request merged**
