### PR TITLE
Prop Validation - add Array default value

### PR DESCRIPTION
**Pull request by ramiy**
Add prop validation for an Array type with a default value using an anonymous function

### CODE REVIEW

**Comment by Justineo** [comment]
https://github.com/vuejs/vuejs.org/blob/5e1911b73ca0b7866436ae3c0daae4a73ee8fb3b//src/v2/guide/components-props.md#L208-L209

**Comment by ramiy** [comment]
@Justineo This comments should not be displayed in the code example, it should be part of the content, maybe a "Tip" style.

**Comment by ramiy** [comment]
@Justineo The code was updated.

The PR adds an example for Array defaults and moves the code comment to the content area.

**Comment by ramiy** [comment]
@Justineo ?

**Comment by sdras** [comment]
Thanks for the PR! I don't really think this change is necessary, it's pretty straightforward now, and this means a lot more reading and scanning. We would also then have two "tips" next two eachother which we don't do. Appreciated, though!

**Pull request closed without merging**
