### PR TITLE
added activate hook into API hooks list

### PR DESCRIPTION
**Pull request by fullfs**
To my point of view the hook is missing in the hooks list at API page. Fixed that :)

### CODE REVIEW

**Comment by fullfs** [comment]
@yyx990803 ping :)

**Comment by yyx990803** [comment]
I think this needs a bit more explanation because the hook is special in that it expects a callback and has async implications. Better to explain that right here in the API reference (and with an example).

**Comment by posva** [comment]
ping @fullfs 
Any progress on this?

**Comment by chrisvfritz** [comment]
Closing due to inactivity, but just opened [a new PR](https://github.com/vuejs/vuejs.org/pull/381) to re-attempt this change.

**Pull request closed without merging**
