### PR TITLE
added an additional hint for transition-classes

### PR DESCRIPTION
**Pull request by krishnanandula**
with Ref to the issue reported here https://github.com/vuejs/vuejs.org/issues/2195.

Please review and let me know if this is the right place to add the additional hint on transition classes.

### CODE REVIEW

**Comment by NataliaTepluhina** [comment]
@krishnanandula thank you for working on this PR! The subject of the mentioned issue was a clarification about group/list transition; so I think it's better to move an additional hint to `List transitions` section.

**Comment by krishnanandula** [comment]
@NataliaTepluhina thanks for the clarification, I will move 
under List Transition section.

**Comment by krishnanandula** [comment]
@NataliaTepluhina  done ! can you please check and let me know if that's the right place to add? or please suggest any changes if needed.

**Comment by NataliaTepluhina** [comment]
@krishnanandula thank you! Now it's definitely a right place 👍

**Pull request merged**
