### PR TITLE
Add Algolia docsearch

### PR DESCRIPTION
**Pull request by maxiloc**
This PR add [Algolia docsearch](https://community.algolia.com/docsearch/) to the vuejs doc.

You can see it live here: [https://vuejs.algolia.com/guide/](https://vuejs.algolia.com/guide/)

Here is a preview:

mzvzyfxja0

### CODE REVIEW

**Comment by yyx990803** [comment]
@maxiloc we are live! Thanks a lot, this is awesome!

**Comment by yyx990803** [comment]
@maxiloc btw, we can totally use this also for http://guide.meteor.com/ - feel free to submit a PR at https://github.com/meteor/guide/tree/master/site , it's also using Hexo :)

**Comment by redox** [comment]
Looks great guys :+1:

**Comment by maxiloc** [comment]
@yyx990803 Glad that you like it, will work on the meteor one tomorrow

**Comment by hootlex** [comment]
Very useful, good job :+1:

**Comment by kazupon** [comment]
@maxiloc 
Great !! :+1: 

Can we support [the japanese translation site](http://jp.vuejs.org)?
That's hosted with [vuejs/jp.vuejs.org](https://github.com/vuejs/jp.vuejs.org) repository.

**Comment by yyx990803** [comment]
@maxiloc sorry to bother you again, but we recently moved the Chinese docs to a slightly different domain so that it is faster to access for Chinese users (DNS inside China): http://vuejs.org.cn/

Would you mind adding an index for that site instead of the previous `cn.vuejs.org`? I sure hope there's an automated way to do this myself, but it seems there is none yet.

**Comment by maxiloc** [comment]
@yyx990803 Just fixed it. For now we need to modify our crawler manually.
We are on the way to automate everything and let you fix those kind of issues by yourself.
Feel free to ping me anytime if you have any issue (We are pretty reactive :smile:)

**Comment by yyx990803** [comment]
@maxiloc wow that's fast - thanks for the awesome support :+1:

**Pull request merged**
