### PR TITLE
Added clarification for in-DOM props and string templates

### PR DESCRIPTION
**Pull request by ivansieder**

### CODE REVIEW

**Comment by leopiccionia** [comment]
You have a typo: `<tempalte>` => `<template>`.

**Comment by ivansieder** [comment]
Thanks @leopiccionia, fixed!

**Comment by ivansieder** [comment]
Thanks @Justineo for the valuable input. I have updated the docs now to have this in a completely separate page and linked it in the props file, too. Would love to get feedback on that one. It's just a first draft for now. So any input is very appreciated!

**Comment by NataliaTepluhina** [comment]
Related to #1807

**Pull request closed without merging**
