### PR TITLE
fixed spanish language typo in dropdown menu

### PR DESCRIPTION
**Pull request by Yilber**
español > Español

### CODE REVIEW

**Comment by Yilber** [comment]
@NataliaTepluhina You're welcome!

**Comment by phanan** [comment]
Hmm? AFAIK you don't capitalize language names in Spanish. For example, this is from Google's setting page:

image

**Comment by Yilber** [comment]
The rule says that language's name belongs to the common names category, therefore, you should not capitalize ingles, frances etc. The problem is that the rule does not tell you what to do when you are listing those names. The common approach is to capitalize the first letter when you are making a list.

You can also find the following on google too if you go to [language setting on the account's page](https://myaccount.google.com/language)

image

**Comment by Yilber** [comment]
@phanan I got in touch with the RAE. I will keep you updated once they provide any feedback on this subject.

**Comment by Yilber** [comment]
@phanan, @NataliaTepluhina here is the response from the RAE about the language names in dropdown menus. https://twitter.com/RAEinforma/status/1217013057118986240

It seems that Google made a small mistake.

**Comment by phanan** [comment]
TIL, thanks @Yilber!

**Pull request merged**
