### PR TITLE
Clarify status of Web Components standard

### PR DESCRIPTION
**Pull request by TimvdLippe**
The standard has been finalized and is shipping in the next version of Firefox. I therefore updated the wording to reflect this status.

### CODE REVIEW

**Comment by phanan** [comment]
Thanks for the PR! Can you link us to the current status, though? Google fails me this time.

**Comment by phanan** [comment]
@TimvdLippe forgive my ignorance (I'm not exactly familiar with web components) but isn't HTMLImport still a working draft according to [MDN](https://developer.mozilla.org/en-US/docs/Web/Web_Components#Specifications)?

**Comment by TimvdLippe** [comment]
@phanan No problem at all. The HTML Import standard has been abandoned, as Mozilla have stated they are not going to implement it.

**Comment by TimvdLippe** [comment]
@phanan Is there anything else you would like to be clarified before this PR can be merged in?

**Comment by phanan** [comment]
@TimvdLippe Not really – I was actually waiting for another opinion from the core members, but I guess this is good enough :) Thanks for the PR!

**Comment by TimvdLippe** [comment]
Awesome thanks!

**Pull request merged**
