### PR TITLE
Adds deploying to firebase to cookbook

### LINKED ISSUE #1585: [Cookbook] Basic deployment to firebase hosting
I'd like to contribute a quick recipe to describe the simplest way to deploy vue-cli to firebase hosting. 
This is introductory level, the purpose of it is to help new users quickly deploy. It is not meant to be a best practice in industry standard production deployments.

### PR DESCRIPTION
**Pull request by WillowHQ**
I tried to make this as explicit as possible.
Please let me know if I need to change anything. 
And yes Canadians say thank you in PRs, thanks !
 
Fixes #1585

### CODE REVIEW

**Comment by sdras** [comment]
Thank you for following up with this, @WillowHQ! I will try to get to a review in a bit.

**Comment by sdras** [comment]
Right away, this recipe doesn't follow the format for cookbook entries. [Please refer to this document](https://vuejs.org/v2/cookbook/index.html#What-we%E2%80%99re-looking-for) for a full rough draft before we review.

**Comment by WillowHQ** [comment]
Ok thanks, will do. Should have it done today.

**Comment by sdras** [comment]
Checking in on this- there's no rush at all! Just wondering if you're still working on it. Thanks!

**Comment by WillowHQ** [comment]
HI Sarah, I submitted a PR to the docs for vue cli, actually not sure if it
has been reviewed yet. I'll go check.

**Comment by sdras** [comment]
Hi there! I'm not sure about the status about your other PR, but I'm going to close this out in favor of it being added here: [https://cli.vuejs.org/guide/deployment.html#firebase](https://cli.vuejs.org/guide/deployment.html#firebase). I'm also happy to have it live here if that's your intention, but seems like from your earlier comment you'd prefer it over there (that does make sense) and we probably shouldn't duplicate.

Please feel free to reopen if you change your mind. Thanks!

**Pull request closed without merging**
