### PR TITLE
components' documentation update base on issue#4117

### PR DESCRIPTION
**Pull request by MarcoBoffo**
https://github.com/vuejs/vue/issues/4117

I think this resource would be useful for single file components' users.

### CODE REVIEW

**Comment by posva** [comment]
Thanks for that! It may indeed help some people, however, the important part is the necessity of lazy loading. This can be achieved in many different ways and depends on the bundler. Also, I think the examples would be clearer if you added the require/import parts for both MyComponent and StackOverflow

**Comment by MarcoBoffo** [comment]
Totally agree with you, tell me if you need anything else.

**Comment by chrisvfritz** [comment]
@MarcoBoffo Thanks for this. Just wanted to let you know that it hasn't fallen off my radar. I'll need to rework this slightly to conform to our internal style guide, but should find time in the next couple days.

**Comment by yyx990803** [comment]
Also - I don't think "recursive" is the correct term here, rather it's about circular references between two components.

**Pull request merged**
