### PR TITLE
Class name should be a string when binding

### PR DESCRIPTION
**Pull request by itainoam**

### CODE REVIEW

**Comment by chrisvfritz** [comment]
Was it not working for you without the quotes?

**Comment by itainoam** [comment]
Yeah, didn't work for me. 
Take a look at this [jsfiddle](https://jsfiddle.net/yMv7y/2011/).
Line 5, if you remove quotes it stops working.

**Comment by LinusBorg** [comment]
That's because Javascript object properties have to be strings if they contain a hyphen (`-`). So that's expected behaviour.

Did you find a place in the docs where we missed to add the quotes in such a case?`Or why did you open this issue?

**Comment by itainoam** [comment]
Got it. Thanks for detailed response!

**Pull request closed without merging**
