### PR TITLE
WIP: Re-order Plugins page

### PR DESCRIPTION
**Pull request by LinusBorg**
- First explain what plugins are and what kinds of plugins exist
- Then explain how to use them.
- Finally, for the "advanced users", explain how to write them.

### CODE REVIEW

**Comment by LinusBorg** [comment]
@chrisvfritz what do you think?

**Comment by phanan** [comment]
@LinusBorg I think this change makes perfect sense. Is it still WIP, though?

**Comment by LinusBorg** [comment]
>  Is it still WIP, though?

Only insofar as I wanted feedback. I don't have anything more to add.

**Comment by phanan** [comment]
Great! I'll take the liberty to go ahead and merge it then :)

**Pull request merged**
