### PR TITLE
Add Firefox to Debugging in VS Code recipe

### PR DESCRIPTION
**Pull request by caugner**

### CODE REVIEW

**Comment by phanan** [comment]
Personally, I feel it clumsy to add " / Firefox" everywhere. Maybe some `p.tip` at the beginning of the recipe works better.

**Comment by sdras** [comment]
I agree with @phanan, I think it would be better to have one single declaration that it's both browsers and avoid the repetition, except where it's necessary to show two ways of working. Let me know if you need some more detailed suggestions on phrasing :)

**Comment by caugner** [comment]
@sdras Thanks for the review. I have just updated the recipe, avoiding (or shortening) the repetition where possible.

Let me know if the PR needs further adjustments.

**Comment by sdras** [comment]
Nicely done! Looks very clean. 👍Thank you @caugner.

**Pull request merged**
