### PR TITLE
Code of conduct adjustment

### PR DESCRIPTION
**Pull request by Haeresis**
Hi @chrisvfritz and @sdras,

Some adjustment I suggest for the Code of conduct, see below the list and reason :

- In order to easily track number line changes and let editor to correctly display content (with wrapping or not), each paragraph is on one line (as all others page in documentation).
- In order to keep a consistency, all unordered list start `*` are replaced by `-`.
- Because we speak about « political attacks », I add the political opinions in the introduction paragraph.
- Because the term “race“ is not neutral, I suggest to split and replace it by, “genotype and phenotype“.

EDIT : Because that will be asked, I replace the scientifc terms « genotype and phenotype » by the original one.

### CODE REVIEW

**Comment by sdras** [comment]
Hi @Haeresis! Thank you for fixing the formatting on the document. We shouldn't change the content here, particularly from `race` to `phenotype and genotype`. It's a code of conduct, we need to cover race explicitly. That's very important. Otherwise, looks good. 👍

**Comment by Haeresis** [comment]
We need also to remove « political opinions » ?

**Comment by chrisvfritz** [comment]
Hey @Haeresis - I talked to Sarah about the political part and we both agreed with you that we do want to protect people based on their political _affiliations_, but want to be careful not to excuse behavior that's otherwise a violation of the code of conduct, based on political views. What do you think of the updated text? @sdras Your thoughts?

Regarding race, I can absolutely see where you're coming from, but the way we talk about it here, it isn't so much referring to genotypical or phenotypical differences as it is to cultural identities and historical patterns of discrimination that are often broader than genotype and phenotype. In English at least, "race" is the currently the best word we have to describe this and in the United States, it also includes specific, important legal protections. Does that make sense?

**Comment by posva** [comment]
I'm honoured you invite me to the conversation but my knowledge regarding wordings in general is very limited. I'm a very clumsy person regarding words so I mostly follow other people's advice 😄 
Chris and Sarah are way far beyond me and are also English native speakers, which I think matters a lot here

**Comment by sdras** [comment]
Well said, Chris, thank you

**Comment by chrisvfritz** [comment]
@Haeresis I'm merging this for now, as I already feel it's a great improvement (thank you!), but please don't hesitate to comment further as continued tweaks are welcome. 🙂

**Comment by sdras** [comment]
Nice job everyone!

**Comment by Haeresis** [comment]
Great job everyone \o/ It's Good to me.

Maybe « cultural identities and historical patterns » in places of « race » could be a great first step :P

**Comment by MachinisteWeb** [comment]
@sdras @chrisvfritz @posva

So I use the decision from Donjon & Dragon to remove « race » to invite you think again about the question ;)

https://screenrant.com/dungeons-dragons-5e-dnd-race-species-change/

**Pull request merged**
