### PR TITLE
Add another caveat I found.

### PR DESCRIPTION
**Pull request by xinbenlv**

### CODE REVIEW

**Comment by Justineo** [comment]
This is not correct. Vue will take care of array methods for you:

https://jsfiddle.net/Justineo/rjgLwm10/

**Comment by xinbenlv** [comment]
@Justineo  Thanks for a quick response.
Here is a shortest version I have for my case.
https://jsfiddle.net/mzL31sfq/2/

**Comment by Justineo** [comment]
https://vuejs.org/v2/guide/list.html#Object-Change-Detection-Caveats

https://jsfiddle.net/Justineo/n1buf3sp/

**Comment by phanan** [comment]
Thanks for the PR, but the information is incorrect as @Justineo has pointed out.

**Pull request closed without merging**
