### PR TITLE
Extended watch API documentation

### PR DESCRIPTION
**Pull request by hitautodestruct**
Added another example of how to use watch handler and elaborated on `deep` comment.

### CODE REVIEW

**Comment by phanan** [comment]
I think this change makes a lot of sense, thanks!

**Comment by Justineo** [comment]
Why change `d` into using a method name here?

**Comment by hitautodestruct** [comment]
It's an example of using a method name inside of a watcher definition.
It just shows there is an option to do so and how to do it.

**Comment by Justineo** [comment]
Oh, it makes sense. Maybe we can add some explanation on this too? The original comment focused on the `immediate` part.

**Comment by hitautodestruct** [comment]
Two options then:
1) We make another example that includes just the handler as a method name.
2) We add a sub comment to the immediate property.

Since there were two examples of functions as method handlers I simply
changed one. But could have easily added another example.

What do you think?

**Comment by Justineo** [comment]
To me, a sub comment should suffice.

**Pull request merged**
