### PR TITLE
[Doc EN]: remove `Single-file component top-level element order` from  `style-guide/index.md`

### PR DESCRIPTION
**Pull request by Haeresis**
As discussed below with @chrisvfritz, we removed this part which really depends on prefered usage of `.vue` file.

> If you submit a PR to the Style Guide removing the part that recommends a specific order, it will be accepted.

— https://github.com/vuejs/vuejs.org/issues/1246#issuecomment-343671331

### CODE REVIEW

**Comment by Haeresis** [comment]
I'm not sure you watch closed issue (and it's normal) so I highlight you an answer I do about an adding in Styleguide : 
— ...

**Comment by chrisvfritz** [comment]
Thanks! I think I miscommunicated though. 😅 I actually meant only remove the part that dictates a _specific_ order. I still want to keep the rule suggesting a consistent order within the project, because I still think consistency is helpful. Does that make sense?

**Comment by chrisvfritz** [comment]
Also, thanks for the ping about that closed issue. I'll take a closer look and give feedback.

**Comment by Haeresis** [comment]
Absolutely! And I prefer just reorder it like I initially suggest! Cool! I
will change this PR!

**Comment by Haeresis** [comment]
Ok @chrisvfritz, it done.

Just need your through about: https://github.com/vuejs/vuejs.org/issues/1245#issuecomment-342426331

**Pull request merged**
