### PR TITLE
Update the Vue's URL in <script> tag

### PR DESCRIPTION
**Pull request by alxmcr**
Hello everybody,

I would like to share my humble change and reason for change. Today, I have been practicing with Props validation exactly with keywords: required, default and validator. I reviewed the Vue Official Documentation [Vue documentation] (https://vuejs.org/v2/guide/#Getting-Started) and it suggest us that we use this code line in our application:

```html
<script src="https://cdn.jsdelivr.net/npm/vue"></script>
```

I used it, but unfortunately, I had unexpected results. For example: I tried to tested the required keyword for `location` property when I pass as value: `Japan`, but it didn't works, Browser's console didn't show any error message for the validation. 

```javascript
{
	name: "Mauricio",
	email: "mauricio@mail.com",
	profile: "https://randomuser.me/api/portraits/men/45.jpg",
	location: "Japan"  // for validation
}
```

Then I researched in Internet: Google, StackOverFlow, forums, etc, but I couldn't any answer.

**Note.-** All this steps, I did in my computer. 

So, I was preparing a Codepen as last resource for Vue Community in Discord. But, for surprise, I didn't have any problem. The Browser's console  showed error messages for the validation. 

ok_vue_validation

Great! ... but why?

I checked the code in Codepen's and my computer. So, I identified that the *difference* was **Vue.js versions**.  

differents_vue_versions

- `Vue.js v2.5.15` - Codepen's code
[Vue.js - Prop Validation - OK](https://codepen.io/maurroj/pen/dmovPg)
- `Vue.js v2.5.13` - My computer code (or suggestion of the Vue documentation)
I also copied this code to Codepen 
[Vue.js - Prop Validation - with unexpected results](https://codepen.io/maurroj/full/pLJaMB)

So, I change the Vue.js URL to solve my problem:

```html
<script src="https://unpkg.com/vue"></script>
```

vue_correction

The problem was resolved 😄!

I hope you like my humble suggestion. Corrections or comments are completely welcome. Have a nice day!

### CODE REVIEW

**Comment by MartinKolarik** [comment]
The code is cached at the CDN for some time for obvious reasons, and also in your browser - that's how both jsDelivr and unpkg work and what can cause minor differences like this (I would say this was just your browser cache in this case). You should be getting 2.5.15 with jsDelivr right now.

@chrisvfritz btw jsDelivr has an API for purging the CDN cache, so if you guys want this url updated immediately after making a new release (rather than with up to 24 hour delay), just send a GET request to `https://purge.jsdelivr.net/npm/vue` after `npm publish`

**Comment by alxmcr** [comment]
Thanks so much for your answer! 😁

I cleared the my browser cache. Yes, you have reason, I got the latest version: `v2.5.15`. Thanks! 😃

Unfortunately I think there still be a difference in the code, because my problem continues. One shows me the validation error messages and another not. 

- ❌[Code doesn't show validation messages](https://codepen.io/maurroj/full/pLJaMB) 

1_vue_does_not_show_messages

the latest version: `v2.5.15` (https://cdn.jsdelivr.net/npm/vue)

- ✔️[Code shows validation messages](https://codepen.io/maurroj/full/dmovPg)

2_vue_does_show_messages

the latest version: `v2.5.15` (https://unpkg.com/vue)

Also, I saw in the dev tools **many attempts** to download Vue:

3_many_files

I would like to compare the two codes but one is minified and another not. Please, can you help me, any suggestion?

**Comment by MartinKolarik** [comment]
Ok I see the problem now. jsDelivr serves the minified version by default (dev is at https://cdn.jsdelivr.net/npm/vue@2.5.15/dist/vue.js), unpkg serves the development version. That validation is only present in the dev version.

**Comment by alxmcr** [comment]
Great! I changed it with your suggestion and the problem was solved. Thanks! 😃

[Codepen resolved](https://codepen.io/maurroj/full/pLJaMB)

- **Codepen's settings**

4_pen_settings

- **Codepen's console**

5_codepen_console

Now, I can see the validation error messages. 👍Thanks! 

I'm sorry. Then, your conclusion is **right**. Is the problem caused by jsDelivr?

**Comment by chrisvfritz** [comment]
@alxmcr @MartinKolarik Thanks to you both! 🙂 I've updated this PR to include both dev and prod versions of the script, noting the difference for users.

**Pull request merged**
