### PR TITLE
Light method refactoring

### PR DESCRIPTION
**Pull request by NogrTL**
Light refactoring that uses method declaration and arrow function

### CODE REVIEW

**Comment by sdras** [comment]
Yes, it's intentional, we had talked about the possibility of changing it. (Informally, so perhaps not the final call).

**Comment by NogrTL** [comment]
@Justineo 
As far as I know it's supported with all browsers with latest version, except the IE.

**Comment by sdras** [comment]
The use of ES5 is indeed intentional. We have talked briefly about updating the docs but I think if we did, we'd have to do a large sweep of everything. Pining @chrisvfritz in case I'm mistaken.

**Comment by NogrTL** [comment]
I'll be nice then to mention that you can use those(method shorthand and arrow function instead of binding this to variable) and warn users that IE doesn't support those features, for example.

**Comment by phanan** [comment]
As everyone else said, ES5 usage in the docs (except for the cookbook) is intentional. Personally, I'd like to keep it as-is (as Vue will continue supporting IE11 even in 3.0) and even if we switch to ES2015, the scope will be much larger than just this `computed.md`. As such, I'm taking the liberty to close this PR :)

**Pull request closed without merging**
