### PR TITLE
another pair of minor typos fixed

### PR DESCRIPTION
**Pull request by gbezyuk**
Now it's just two mispositioned spaces. Which is good )

### CODE REVIEW

**Comment by gbezyuk** [comment]
Hmm, once again it doesn't see previously merged commits. I have no idea why, honestly. o_O.

**Comment by chrisvfritz** [comment]
Try this (assuming your branch's remote is `origin` and our is `official`)

1. `git fetch official`
2. `git checkout -b tmp-branch
3. `git reset --hard official/master`
4. `git cherry-pick COMMIT_SHAS_FROM_PREVIOUS_BRANCH`
5. `git push origin tmp-branch:original-typo-fixes`

**Comment by chrisvfritz** [comment]
Just fixed these in a separate commit, crediting you. Thanks!

**Comment by gbezyuk** [comment]
Thanks! Sorry, I've got focused on translation and didn't pay enough attention to this PR.

**Comment by chrisvfritz** [comment]
Not a problem. 😃

**Pull request closed without merging**
