### PR TITLE
Update Webpack links

### PR DESCRIPTION
**Pull request by LinusBorg**
Replaced all links to web pack.github.io with their counterparts on wepack.js.org

### CODE REVIEW

**Comment by LinusBorg** [comment]
@chrisvfritz 

This should also be done in all community translations. How do we coordinate these changes?

**Comment by chrisvfritz** [comment]
Looks great. Translation master @gbezyuk 😄  - anything special you think we should do to coordinate this change across translations?

**Comment by gbezyuk** [comment]
@chrisvfritz the best way is simply to create PRs in translation repos, obviously ) or at least issues, if the actual job is to be delegated.
thanx for the title, BTW =)

**Comment by gbezyuk** [comment]
@Alex-Sokolov please take a look

**Comment by Alex-Sokolov** [comment]
@gbezyuk done in https://github.com/translation-gang/ru.vuejs.org/pull/115

**Pull request merged**
