### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by Runrioter**
tweaks data source to make it work well

### CODE REVIEW

**Comment by nickmessing** [comment]
@Runrioter, `app.message` and `app2.message` work well while `app.__vue__` is undefined, where did you get that from?

**Comment by nickmessing** [comment]
Screenshot

**Comment by Runrioter** [comment]
@nickmessing   I set up a project with vue-cli. I did as what documents said.
image

**Comment by Runrioter** [comment]
@nickmessing  I got it,  if use UMD, it works well as documents said. If use with a bundler like webpack, it does't.

**Pull request closed without merging**
