### PR TITLE
Refactor Themes section

### PR DESCRIPTION
**Pull request by phanan**
As discussed, this PR refactors the Themes section out of the current Examples page and into its own page. 

We'll also need the contact email.

### CODE REVIEW

**Comment by phanan** [comment]
Ignore commit aa9b567, I mistakenly included it into the PR, but it shouldn't have any bad effect.

**Comment by yyx990803** [comment]
Should the "new" dot be shown for the top level Theme link instead?

**Comment by phanan** [comment]
@yyx990803 Oops, totally missed that. Fixed.

Also, what do you reckon the contact email should be, and how can we make it clearer that this is an affiliation-only page (if necessary)?

**Comment by bencodezen** [comment]
Nice job with theme page!

My only feedback is that putting it in the main navigation is giving it too much prominence especially since it's an affiliation-only page. It almost feels like we're selling ad space on the site.

Instead, I would recommend that we put it in the "Ecosystem" dropdown instead.

**Comment by phanan** [comment]
@bencodezen I thought about exactly that: the ecosystem dropdown. Problem is, this dropdown is already so long that having the Themes item there would be not much better than the current Examples when it comes to exposure, thus defeat the purpose of this refactor in the first place.

**Comment by bencodezen** [comment]
@phanan What if we surface the entire subsection of "Resources" instead since that includes other curated links that has a more open-source vibed rather than affiliates only? That would simultaneously reduce the Ecosystem dropdown list length while helping to better surface everything at once.

What do you think?

**Comment by yyx990803** [comment]
Looks good - can you resolve the conflicts?

**Comment by phanan** [comment]
@yyx990803 Done. I've also moved the Partners page to under Resources as we discussed and fixed some menu/sidebar issues.

**Pull request merged**
