### PR TITLE
More information about list render

### LINKED ISSUE #665: More information about list render
refer: https://github.com/vuejs/vue/issues/4512

1. v-for has higher priority
2. additional note with v-for and v-if api

### PR DESCRIPTION
**Pull request by defcc**
fix #665

### CODE REVIEW

**Comment by defcc** [comment]
Thanks @kazupon , I'll update it.

**Comment by defcc** [comment]
updated.

**Comment by chrisvfritz** [comment]
Looks great! I'll try to tweak this a tiny bit more, then merge later today.

**Comment by kazupon** [comment]
@defcc thanks updating!
LGTM 👍

**Comment by chrisvfritz** [comment]
I'm going to finish tweaking this locally, thanks!

**Pull request merged**
