### PR TITLE
Image path Update

### PR DESCRIPTION
**Pull request by andela-iadeniyi**
Update the image path in the hackernews.md documentation

### CODE REVIEW

**Comment by LinusBorg** [comment]
I don't think it's a good idea to add absolute link to the repository. this link would persist through all forks of this repo, and all forks would break if we wver thange our repo's content.

**Comment by andela-iadeniyi** [comment]
Yes, the images doesn't display. I get your point, I'll have to make the path relative.

**Comment by chrisvfritz** [comment]
Images seem to display for me. Are you looking at [http://vuejs.org/examples/hackernews.html](http://vuejs.org/examples/hackernews.html)?

**Comment by andela-iadeniyi** [comment]
I'm looking at https://github.com/vuejs/vuejs.org/blob/master/src/examples/hackernews.md.

**Comment by chrisvfritz** [comment]
Ah, I see. The docs aren't actually made to be read from GitHub. They only render to HTML because that's what GitHub does with Markdown files.

**Pull request closed without merging**
