### PR TITLE
Optimized images

### PR DESCRIPTION
**Pull request by Alex-Sokolov**
with https://kraken.io/web-interface to make pages a little bit faster :)

### CODE REVIEW

**Comment by yyx990803** [comment]
Thanks, can you share some size comparison before/after?

**Comment by chrisvfritz** [comment]
I noticed that some colors are slightly different post-optimization. For example, compare the greens below:

screen shot 2018-01-16 at 11 12 27 am

**Comment by Alex-Sokolov** [comment]
@yyx990803 sure

`src/images/`

file | original | optimized | savings
-- | -- | -- | --
dom-tree.png | 58.22 KB | 14.76 KB | 43.46 KB
lifecycle.png | 61.66 KB | 56.60 KB | 5.06 KB
logged-proxied-data.png | 58.61 KB | 18.26 KB | 40.35 KB

` themes/vue/source/images`

file | original | optimized | savings
-- | -- | -- | --
100offer.png | 5.02 KB | 2.67 KB | 2.35 KB
anymod.png | 11.33 KB | 4.45 KB | 6.88 KB
coin-bch.png | 12.50 KB | 512 B | 12.00 KB
coin-btc.png | 12.32 KB | 502 B | 11.83 KB
coin-eth.png | 12.46 KB | 516 B | 11.95 KB
coin-ltc.png | 12.00 KB | 493 B | 11.52 KB
conf.png | 12.47 KB | 4.94 KB | 7.53 KB
datacamp.png | 24.54 KB | 7.01 KB | 17.52 KB
famebroker.png | 6.31 KB | 3.73 KB | 2.57 KB
frontend-love.png | 15.61 KB | 7.35 KB | 8.26 KB
frontend-meetups.png | 15.56 KB | 6.36 KB | 9.20 KB
infinitynewtab.png | 51.16 KB | 20.40 KB | 30.76 KB
neds.png | 12.93 KB | 7.37 KB | 5.56 KB
onsen-ui.png | 28.46 KB | 14.93 KB | 13.53 KB
paypal.png | 7.89 KB | 4.62 KB | 3.27 KB
stdlib.png | 22.82 KB | 11.56 KB | 11.26 KB
tooltwist.png | 18.41 KB | 8.58 KB | 9.84 KB
vuejobs.png | 13.89 KB | 6.91 KB | 6.98 KB
vuejsadmin.png | 26.36 KB | 10.57 KB | 15.79 KB
vueschool.png | 29.81 KB | 10.02 KB | 19.79 KB
vuetify.png | 15.95 KB | 6.37 KB | 9.57 KB
xfive.png | 14.45 KB | 6.72 KB | 7.73 KB

` themes/vue/source/images/icons`

file | original | optimized | savings
-- | -- | -- | --
android-icon-36x36.png | 1.73 KB | 1.07 KB | 681 B
android-icon-48x48.png | 2.15 KB | 1.49 KB | 675 B
android-icon-72x72.png | 2.69 KB | 1.91 KB | 797 B
android-icon-96x96.png | 3.54 KB | 2.14 KB | 1.41 KB
android-icon-144x144.png | 5.46 KB | 3.08 KB | 2.38 KB
android-icon-192x192.png | 6.39 KB | 3.28 KB | 3.11 KB
apple-icon-57x57.png | 2.22 KB | 1.47 KB | 761 B
apple-icon-60x60.png | 2.38 KB | 1.62 KB | 776 B
apple-icon-72x72.png | 2.69 KB | 1.91 KB | 797 B
apple-icon-76x76.png | 2.96 KB | 2.01 KB | 974 B
apple-icon-114x114.png | 4.26 KB | 2.50 KB | 1.75 KB
apple-icon-120x120.png | 4.46 KB | 2.61 KB | 1.85 KB
apple-icon-144x144.png | 5.46 KB | 3.08 KB | 2.38 KB
apple-icon-152x152.png | 5.64 KB | 3.20 KB | 2.44 KB
apple-icon-180x180.png | 7.18 KB | 3.87 KB | 3.31 KB
apple-icon-precomposed.png | 6.95 KB | 3.28 KB | 3.67 KB
apple-icon.png | 6.95 KB | 3.31 KB | 3.64 KB
favicon-16x16.png | 1.09 KB | 482 B | 635 B
favicon-32x32.png | 1.82 KB | 1.17 KB | 670 B
favicon-96x96.png | 3.54 KB | 2.14 KB | 1.41 KB
ms-icon-70x70.png | 2.58 KB | 1.80 KB | 799 B | 30.19 % | Download File
ms-icon-144x144.png | 5.46 KB | 3.08 KB | 2.38 KB | 43.58 % | Download File
ms-icon-150x150.png | 5.64 KB | 3.09 KB | 2.55 KB | 45.25 % | Download File
ms-icon-310x310.png | 15.88 KB | 7.51 KB | 8.37 KB | 52.71 %

**Comment by Alex-Sokolov** [comment]
@chrisvfritz you right, didn't notice that! I think better to revert icons folder

**Comment by chrisvfritz** [comment]
@Alex-Sokolov Thanks for this! I like saving space on images, but I'm going to merge #1389 instead of this one though, as some of these optimizations seem to be a _little_ too aggressive, causing slight alterations.

**Pull request closed without merging**
