### PR TITLE
Why not add v-on:resize support and others...

### PR DESCRIPTION
**Pull request by d4g0**
Hey there, i will love to be able to do things like “ v-on:resize “ , “ v-on:load “, and so other coolish v-on unborn directives.
Also i have doubts if there is available other events
For the v-on directive, besides the clasics click, submit,
Keyup-down, if that is they case they should be included in the officials docs.

### CODE REVIEW

**Comment by Justineo** [comment]
Please follow contribution guidelines instead of making an invalid PR like this.

**Comment by d4g0** [comment]
Hey Gu, what are the  contribution guidelines that i can follow here my friend, im totally newbie and have no idea, im sorry if i cause you some trouble


Sent with 💚 from havana

**Comment by Justineo** [comment]
When filing new issue in vuejs/vue you will see an issue template. Just follow the instructions there should be fine.

**Comment by bencodezen** [comment]
@d4g0 Did you mean to create an issue rather than issue a PR?

**Pull request closed without merging**
