### PR TITLE
Add note about single file components

### PR DESCRIPTION
**Pull request by Qrokqt**

### CODE REVIEW

**Comment by phanan** [comment]
Thanks for your contribution, but I think 1/ the quality of the PR isn't up to our standards and 2/ more importantly, it's incorrect – `key` is a core concept and works anywhere Vue.

**Comment by Qrokqt** [comment]
@phanan v-if on template does not work single file components.

**Comment by Justineo** [comment]
It works.

**Comment by Qrokqt** [comment]
Are you saying this code, when copied directly from the docs works for you in single file components? Because it doesn't for me.

```
<template v-if="loginType === 'username'">
  <label>Username</label>
  <input placeholder="Enter your username">
</template>
<template v-else>
  <label>Email</label>
  <input placeholder="Enter your email address">
</template>
```

**Comment by phanan** [comment]
@Qrokqt Please note that `<template>` can be used at a non-root level as well, as a transparent wrapper, e.g.

```
<template>
  <div>
    <template v-if="loginType === 'username'">
      <label>Username</label>
      <input placeholder="Enter your username">
    </template>
    <template v-else>
      <label>Email</label>
      <input placeholder="Enter your email address">
    </template>
  </div>
</template>

**Pull request closed without merging**
