### PR TITLE
Added section discussing computed array

### PR DESCRIPTION
**Pull request by hitautodestruct**
Added a section that explains the use of computed setters on an array. Specifically the use of methods such as push to manipulate a computed property.

### CODE REVIEW

**Comment by phanan** [comment]
Thanks for the PR, but I find it pretty confusing. There's no acessing/mutating to the computed property `participants` in your example, for instance. Even if you meant for `this.names` to be `this.participants` instead, it would be a getter and not a setter. Can you explain?

**Comment by hitautodestruct** [comment]
Yes, you're right the push was on `this.participants` and note `this.names`, I fixed the commit.

Basically the idea is to let the reader understand that when dealing with setters on an array when using `.push`,`.shift` etc. vue will pass in the entire array and not just the single `.push`ed property.

**Comment by phanan** [comment]
It's incorrect then. `participants` appears to be a string (its getter uses `Array.join()` which returns a string), so calling `participants.push(fullName)` will simply not work. There's no mutator in your code as well – like I said above, you have an accessor.

**Comment by hitautodestruct** [comment]
@phanan I see now, what you mean.
I'm assuming that because I'm not returning an array in `get()` I'm also not able to `set()` the array?
This behaviour should be noted in the docs.

**Pull request closed without merging**
