### PR TITLE
add Circular References Between Components  example

### PR DESCRIPTION
**Pull request by xalexec**

### CODE REVIEW

**Comment by chrisvfritz** [comment]
Thanks for the contribution! Can you please provide a little more detail about the problem you're trying to solve here?

**Comment by xalexec** [comment]
When I read the document, the above fragments make me understand some of the deviation, , so I want to write an example so that others can understand easily.

**Comment by chrisvfritz** [comment]
Is there a way you think we can improve the existing example to make it clearer? For example, is there information we might be missing? I think I'd rather improve the existing example rather than just linking to another one.

**Comment by xalexec** [comment]
I think it's better to provide a complete example than a snippet,this is i can do.

**Pull request closed without merging**
