### PR TITLE
Riot comparison - VueJS interacts better with inline JS

### PR DESCRIPTION
**Pull request by DuskoV**
- Riot doesn't allow direct access to components/tags from inline JS without using complex mixins. Vue has straight-forward approach.

### CODE REVIEW

**Comment by chrisvfritz** [comment]
I'm not personally familiar with trying to use this feature in Riot. If others have used both Vue and Riot and found this to be true (or not true), please comment! 🙂

**Comment by DuskoV** [comment]
I experienced it. For example, if I make AJAX call from regular JS, and want to inject JSON in data component, I can do ot easy in Vue. Riot is another story (need mixin, etc).

**Comment by chrisvfritz** [comment]
@DuskoV We simply want to be careful about adding anything to this page that we don't have first-hand experience with (or clear community consensus on). If you created a couple JSFiddles demonstrating the difference, then I could play around with them and do a little extra research to validate the claim.

**Comment by DuskoV** [comment]
Here you go, Chris:
https://jsfiddle.net/oys8avje/

- Vue allows direct access out from scope (from inline JS)
- Riot requires mixins


Hope this helps.

**Comment by chrisvfritz** [comment]
Hmm, even though I understand what you're saying now and do agree, I worry the use case is a little difficult to explain in a short amount of text and also not encountered that frequently. I do appreciate you helping me learn more about Riot, but I worry about sounding nitpicky by including a (relatively) niche feature like this. It's also introduced very early in the Vue docs, so I think there's less risk in someone missing it.

**Pull request closed without merging**
