### PR TITLE
typescript.md: mentioned support in WebStorm

### PR DESCRIPTION
**Pull request by prigara**
Hi everyone!

Hope you don't mind adding WebStorm to the list of development tools that support Vue.js and TypeScript.

Thank you!

### CODE REVIEW

**Comment by chrisvfritz** [comment]
Thanks!

**Comment by nickmessing** [comment]
Oh, it does? Didn't use it in last 6 months because of vue support :+1:

**Comment by chrisvfritz** [comment]
I definitely have nothing against WebStorm, but I'm hesitating slightly about promoting a paid editor, especially as we don't currently list other editors that may also offer support.

**Comment by chrisvfritz** [comment]
Hm, I'm just going to merge it. Many people enjoy and have already paid for Webstorm. And as @nickmessing just demonstrated, this could be useful information for many of those people. The next time we add an editor, I might expand this out a bit more into an actual list, with more details such as whether the product is free or paid.

**Comment by nickmessing** [comment]
@chrisvfritz, maybe adding license will help? I know a couple of guys that care a lot abut things like GPLv3 vs Apache-2.0

**Comment by chrisvfritz** [comment]
I think that can matter if people want to work on the editor's source code or incorporate the source into another project/product, but as a user of an editor I don't think the license really matters.

**Comment by prigara** [comment]
Thanks!
I think it would be great if there was a page with a list of all editors that support Vue with JS or TS.

**Pull request merged**
