### PR TITLE
Update comment at cookbook-unit-testing

### PR DESCRIPTION
**Pull request by ykhirao**
@ here 
cc: @lmiller1990 

I'm translating [Unit Testing Vue Components](https://vuejs.org/v2/cookbook/unit-testing-vue-components.html) from English to Japanese at [this issue](https://github.com/vuejs/jp.vuejs.org/issues/822) now!!

Could you review my PR?
An error occurs if it is less than 7 characters so I changed from `longer ` to `no longer`.

Thank you for reading this to the end 👍

### CODE REVIEW

**Comment by lmiller1990** [comment]
Good catch @ykhirao . Only the core team members can merge to master - I'm sure someone will merge this soon. 

I'm excited to see my cookbook contribution translated into Japanese! The Vue.js-jp usergroup is great, no wonder Vue.js is so popular in Japan.

**Comment by sdras** [comment]
nice catch :)

**Comment by ykhirao** [comment]
@lmiller1990 Thank you!! Please wait my translation 👍 
@sdras Thank you :)

**Comment by kazupon** [comment]
@ykhirao @lmiller1990 Thanks! :)

**Pull request merged**
